### ISSUE TITLE
Remove Example 2 from firewall controls

### ISSUE THREAD

**Issue by netapp-aronk** [NetAppDocs/storagegrid-118#10]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/admin/manage-firewall-controls.html

### Page title

Manage internal firewall controls

### Summary

In 11.8 the ports 443, 8443, and 9443 for grid and tenant management were removed from the firewall controls UI and this functionality is no-longer possible.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-aronk, thank you for highlighting this. We will investigate and follow up here.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-aronk, I've opened SGRIDDOC-58 to track this doc request and added you as a watcher.
