### ISSUE TITLE
Subnet links not drawn

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/storagegrid-118#13]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/network/topology-for-all-three-networks.html

### Page title

Topology for all three networks

### Summary

If we already have multiple admin subnets, then they should be connected (red).

![image](https://github.com/NetAppDocs/storagegrid-118/assets/16622642/11eb34d9-1c9d-4d95-a34d-d0b96b11f45b)

Separately, maybe it's time to rebuild these diagrams from the 90s using modern diagramming software.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by scaleoutsean** [comment]
Hi @netapp-pcarriga, 

The problem that see - maybe I'm not interpreting that correctly - is what I wrote in Subject - subnet links for two Admin networks at the bottom are not drawn at all.

At the top I drew two red lines by myself to show what would make sense to me (i.e. if they were connected to somewhere). (Obviously they should be blue, as the rest of admin networks, but then it would have been even harder to spot).

Here's what bottom part of the image looks like: 

![image](https://github.com/NetAppDocs/storagegrid-118/assets/16622642/337f17fb-26b7-4138-af55-5066e87665c4)

For an example, 10.10.2.0/24 isn't connected to anything at all.

> Admin (or Client) subnets be connected. Each node can have a completely different, isolated Admin subnet if desired.

Hmm, okay. I understand that an Admin or client network can be isolated, but surely at least one of the grid nodes must be able to connect to Admin network? 

If 10.10.2.0/24 was a global route on that site at the bottom, blue lines would connect all nodes on the grid to that Admin network. If it's a custom, isolated network, there would be at least one link from one of the grid nodes, connecting it to 10.10.2.0/24. 

Currently there are no links connecting 10.17.100.100/24 and 10.10.2.0/24 to anything, so what does that mean? That no grid node is reachable from those networks? 
Or that there's a custom route from those two Admin networks to the whole grid? If that was the case I'd expect some sort of connection to be shown from 10.10.2.0/24 to all grid nodes similar to what 10.10.1.0/24 has.

**Comment by netapp-pcarriga** [comment]
I've confirmed with Engineering that the documentation correctly describes the topology for the context of the page.
