### ISSUE TITLE
Reference to RHEL in automating installs section

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/storagegrid-118#16]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/ubuntu/index.html

### Page title

Quick start for installing StorageGRID on Ubuntu or Debian

### Summary

Hi,

In the "Automate the installation" section there is a line saying "Installation of RHEL" - I suppose this should be "Installation of Ubuntu or Debian"?

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thank you @estarz . I'll verify and update the documentation as soon as possible.

**Comment by netapp-pcarriga** [comment]
Thank you again @estarz for helping us improve our customer documentation. It now correctly reads "Installation of Ubuntu or Debian": https://docs.netapp.com/us-en/storagegrid-118/ubuntu/index.html#automate-the-installation
