### ISSUE TITLE
Include details on checking for existing procedures

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-118#23]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/troubleshoot/verifying-object-integrity.html

### Page title

Verify object integrity

### Summary

In this page, the user is asked to check whether any other maintenance procedure is running. The list of procedures is provided, but not how. Recently, we had a chat initiated by a customer on the support site and one of their asks after providing the link to this page, is how do I check for all these procedures?

We are not necessarily looking to take a lot of page space to detail how to check each procedure, but maybe having a general page in documentation to explain where to check the status of each procedure and then that page can be just linked here. Just an idea if this is feasible.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp, thanks for this suggestion. I've opened SGRIDDOC-86 to track this request and added you as a watcher.
