### ISSUE TITLE
Improve S3 documentation

### ISSUE THREAD

**Issue by vardhanv** [NetAppDocs/storagegrid-118#25]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/s3/bucket-and-group-access-policies.html

### Page title

Use bucket and group access policies

### Summary

These policies and the conditionals are part of the S3 API spec. Covering them here makes it hard to figure out what the S3 support is. Can these be merged in some way with the S3 documentation.

https://docs.netapp.com/us-en/storagegrid-118/s3/quick-reference-support-for-aws-apis.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
HI @vardhanv, I've opened SGRIDDOC-85 to track this request and added you as a watcher.
