### ISSUE TITLE
Include note about support for SNMP GET

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-118#4]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/monitor/using-snmp-monitoring.html

### Page title

Use SNMP monitoring: Overview

### Summary

The query authentication "Community string" implies we support SNMP GET method but that's not clearly stated in this page. This came in as a question from the a customer to support. It would be good to call out SNMP somewhere in this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @adamn-netapp, thank you for bringing this to our attention. I'm working with the StorageGRID team on how to proceed with regards to updating the documentation.

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp, I've opened SGRIDDOC-53 to track this request internally and I've added you as watcher the ticket.
