### ISSUE TITLE
Storage requirements by node type

### ISSUE THREAD

**Issue by netapp-aronk** [NetAppDocs/storagegrid-118#5]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/vmware/storage-and-performance-requirements.html

### Page title

Storage and performance requirements

### Summary

metadata only node storage requirements is missing 100GB OS disk

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks @netapp-aronk for bringing this to our attention. I've opened SGRIDDOC-55 to track this issue internally, and added you as a watcher.
