### ISSUE TITLE
StorageGRID Amazon SNS endpoints do not support CAP (C2S) authentication

### ISSUE THREAD

**Issue by netapp-bhouser** [NetAppDocs/storagegrid-118#7]
### Page URL

https://docs.netapp.com/us-en/storagegrid-118/tenant/creating-platform-services-endpoint.html

### Page title

Create platform services endpoint

### Summary

The docs incorrectly state that C2S authentication is supported for Amazon SNS endpoints. C2S authentication is only supported for CloudMirror endpoints in 11.8.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-bhouser, I've opened SGRIDDOC-57 to track this doc request and added you as watcher.
